name: video_library

networks:
  video-library-network:
    driver: bridge

volumes:
  postgres-data:

services:
  some-postgres:
    image: postgres:16.2
    networks:
      - video-library-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video-library-spring
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    image: video-library-spring:1.0
    environment:
      DATABASE_URL: jdbc:postgresql://some-postgres:5432/video-library-spring
    networks:
      - video-library-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - some-postgres