app.image.bucket: C:/DevTools/temp/userImage
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          fetch_size: 100
          batch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 133580343976-lrnunjdeudhs964fni39e6a3svd82hpi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile
  servlet:
    multipart:
      max-file-size: 5MB
  messages:
    basename: messages
springdoc:
  swagger-ui:
    oauth:
      client-id: 133580343976-lrnunjdeudhs964fni39e6a3svd82hpi.apps.googleusercontent.com
      client-secret: GOCSPX-KOI5_zkw1EXQ5lYWrcg07CiqKzP
      scopes: openid, email, profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
logging:
  level:
    root: INFO
  file:
    name: application.log
    path: /
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 1MB