INSERT INTO person (person_name, person_birth_date)
VALUES ('Emma Watson', '1990-04-25'),
       ('Brad Pitt', '1963-12-18'),
       ('Danial Radcliffe', '1989-07-23'),
       ('Rupert Grint', '1988-08-24'),
       ('Russel Crowe', '1964-04-07'),
       ('Angelina Jolie', '1975-06-04'),
       ('Tom Cruise', '1962-07-03'),
       ('Peter Jackson', '1961-10-31'),
       ('Orlando Bloom', '1977-01-13'),
       ('Hans Zimmer', '1957-09-12'),
       ('Johnny Depp', '1963-06-09'),
       ('Cameron Diaz', '1972-08-30'),
       ('Kate Winslet', '1975-10-05'),
       ('Nina Dobrev', '1989-01-09'),
       ('Ian Somerhalder', '1978-12-08'),
       ('Paul Wesley', '1982-07-23'),
       ('Zac Efron', '1987-10-18'),
       ('Zendaya', '1996-09-01'),
       ('Christian Bale', '1974-01-30'),
       ('Christopher Nolan', '1970-07-30'),
       ('Leonardo DiCaprio', '1974-11-11'),
       ('John David Washington', '1984-07-28'),
       ('Timothée Chalamet', '1995-12-27'),
       ('Heath Ledger', '1979-04-04'),
       ('Denis Villeneuve', '1967-10-03');

INSERT INTO movie (movie_title, release_year, movie_country, movie_genre, movie_description)
VALUES ('The Dark Knight', 2008, 'the USA', 'ACTION',
        'The plot follows the vigilante Batman, police lieutenant James Gordon, and district attorney Harvey Dent, who form an alliance to dismantle organized crime in Gotham City. Their efforts are derailed by the Joker, an anarchistic mastermind who seeks to test how far Batman will go to save the city from chaos.'),
       ('Inception', 2010, 'the USA', 'SCIENCE_FICTION',
        'Summaries. A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.'),
       ('Tenet', 2020, 'United Kingdom', 'SCIENCE_FICTION',
        'The film follows a former CIA agent who learns how to manipulate the flow of time to prevent an attack from the future that threatens to annihilate the present world.'),
       ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'New Zealand', 'FANTASY',
        'A young hobbit, Frodo, who has found the One Ring that belongs to the Dark Lord Sauron, begins his journey with eight companions to Mount Doom, the only place where it can be destroyed.'),
       ('The Lord of the Rings: The Two Towers', 2002, 'New Zealand', 'FANTASY',
        'Frodo and Sam arrive in Mordor with the help of Gollum. A number of new allies join their former companions to defend Isengard as Saruman launches an assault from his domain.'),
       ('The Lord of the Rings: The Return of the King', 2003, 'New Zealand', 'FANTASY',
        'The former Fellowship members prepare for the final battle. While Frodo and Sam approach Mount Doom to destroy the One Ring, they follow Gollum, unaware of the path he is leading them to.'),
       ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'the USA', 'ADVENTURE',
        'A blacksmith joins forces with Captain Jack Sparrow, a pirate, in a bid to free the love of his life from Jack''s associates, who kidnapped her suspecting she has the medallion.'),
       ('Dune', 2021, 'the USA', 'SCIENCE_FICTION',
        'It is the first of a two-part adaptation of the 1965 novel of the same name by Frank Herbert. Set in the distant future, the film follows Paul Atreides as his family, the noble House Atreides, is thrust into a war for the deadly and inhospitable desert planet Arrakis.'),
       ('Harry Potter and the Sorcerer''s Stone', 2001, 'United Kingdom', 'FANTASY',
        'Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him.'),
       ('Harry Potter and the Chamber of Secrets', 2002, 'United Kingdom', 'FANTASY',
        'A house-elf warns Harry against returning to Hogwarts, but he decides to ignore it. When students and creatures at the school begin to get petrified, Harry finds himself surrounded in mystery.'),
       ('Harry Potter and the Prisoner of Azkaban', 2004, 'United Kingdom', 'FANTASY',
        'Harry, Ron and Hermoine return to Hogwarts just as they learn about Sirius Black and his plans to kill Harry. However, when Harry runs into him, he learns that the truth is far from reality.'),
       ('Harry Potter and the Goblet of Fire', 2005, 'United Kingdom', 'FANTASY',
        'When Harry is chosen as a fourth participant of the inter-school Triwizard Tournament, he is unwittingly pulled into a dark conspiracy that endangers his life.'),
       ('Harry Potter and the Order of the Phoenix', 2007, 'United Kingdom', 'FANTASY',
        'Harry Potter and Dumbledore''s warning about the return of Lord Voldemort is not heeded by the wizard authorities who, in turn, look to undermine Dumbledore''s authority at Hogwarts and discredit Harry.'),
       ('Harry Potter and the Half-Blood Prince', 2009, 'United Kingdom', 'FANTASY',
        'Dumbledore and Harry Potter learn more about Voldemort''s past and his rise to power. Meanwhile, Harry stumbles upon an old potions textbook belonging to a person calling himself the Half-Blood Prince.'),
       ('Harry Potter and the Deathly Hallows: Part 1', 2010, 'United Kingdom', 'FANTASY',
        'After Voldemort takes over the Ministry of Magic, Harry, Ron and Hermione are forced into hiding. They try to decipher the clues left to them by Dumbledore to find and destroy Voldemort''s Horcruxes.'),
       ('Harry Potter and the Deathly Hallows: Part 2', 2011, 'United Kingdom', 'FANTASY',
        'Harry, Ron and Hermione race against time to destroy the remaining Horcruxes. Meanwhile, the students and teachers unite to defend Hogwarts against Lord Voldemort and the Death Eaters.');

INSERT INTO movie_person (movie_id, person_id, person_role)
VALUES (1, 10, 'COMPOSER'),
       (1, 19, 'ACTOR'),
       (1, 20, 'DIRECTOR'),
       (1, 24, 'ACTOR'),
       (2, 21, 'ACTOR'),
       (2, 20, 'DIRECTOR'),
       (3, 22, 'ACTOR'),
       (3, 20, 'DIRECTOR'),
       (4, 8, 'PRODUCER'),
       (4, 8, 'DIRECTOR'),
       (4, 8, 'ACTOR'),
       (4, 9, 'ACTOR'),
       (5, 8, 'PRODUCER'),
       (5, 8, 'DIRECTOR'),
       (5, 8, 'ACTOR'),
       (5, 9, 'ACTOR'),
       (6, 8, 'PRODUCER'),
       (6, 8, 'DIRECTOR'),
       (6, 8, 'ACTOR'),
       (6, 9, 'ACTOR'),
       (7, 9, 'ACTOR'),
       (7, 10, 'COMPOSER'),
       (7, 11, 'ACTOR'),
       (8, 23, 'ACTOR'),
       (8, 25, 'DIRECTOR'),
       (9, 1, 'ACTOR'),
       (9, 3, 'ACTOR'),
       (9, 4, 'ACTOR'),
       (10, 1, 'ACTOR'),
       (10, 3, 'ACTOR'),
       (10, 4, 'ACTOR'),
       (11, 1, 'ACTOR'),
       (11, 3, 'ACTOR'),
       (11, 4, 'ACTOR'),
       (12, 1, 'ACTOR'),
       (12, 3, 'ACTOR'),
       (12, 4, 'ACTOR'),
       (13, 1, 'ACTOR'),
       (13, 3, 'ACTOR'),
       (13, 4, 'ACTOR'),
       (14, 1, 'ACTOR'),
       (14, 3, 'ACTOR'),
       (14, 4, 'ACTOR'),
       (15, 1, 'ACTOR'),
       (15, 3, 'ACTOR'),
       (15, 4, 'ACTOR'),
       (16, 1, 'ACTOR'),
       (16, 3, 'ACTOR'),
       (16, 4, 'ACTOR');

INSERT INTO users (user_name, user_birth_date, user_image, user_email, user_password, role, gender)
VALUES ('user1', '2000-01-01', 'userImage/user1.PNG', 'user1@gmail.com', '12345678', 'USER', 'MALE'),
       ('user2', '1999-01-01', 'userImage/user2.PNG', 'user2@gmail.com', '11223344', 'USER', 'FEMALE'),
       ('user3', '1995-01-01', 'userImage/user3.PNG', 'user3@gmail.com', '98765432', 'USER', 'MALE'),
       ('admin', '1990-01-01', 'userImage/admin.PNG', 'admin@gmail.com', '99887766', 'ADMIN', 'MALE');

INSERT INTO review (movie_id, user_id, review_text, rate)
VALUES (1, 1, 'Nice movie.', 9),
       (1, 3, 'One of my favorite movies. Watched it many times, definitely recommended!', 10),
       (2, 1, 'Such a lovely story, absolutely love it!', 10),
       (2, 3, 'Nolan is so genius', 7),
       (3, 1, 'Good one', 8),
       (3, 3, 'Cool movie', 9),
       (4, 1, 'Great movie', 10),
       (4, 3, 'I really like this movie', 9);